# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

marigold_version = File.read(File.join(__dir__, '.marigold-ios-version'))

# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'
prepare_react_native_project!

target "MarigoldSDKReactNative" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  target "MarigoldSDKReactNativeTests" do
    # Pods for testing
    pod "Marigold", marigold_version
    pod "Marigold-Extension", marigold_version

    pod "Kiwi", "2.4.0"
    pod "OCMock", "3.1.2"
  end
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
    end
  end
end
