require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['RCT_NEW_ARCH_ENABLED'] = '0'
# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'
prepare_react_native_project!

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

target "MarigoldSDKReactNative" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target "MarigoldSDKReactNativeTests" do
    # Pods for testing
    pod "Marigold", "18.1.0"
    pod "Marigold-Extension", "18.1.0"
    pod "Kiwi", "2.4.0"
    pod "OCMock", "3.1.2"
  end
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
