# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target "CarnivalSDKReactNative" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CarnivalSDKReactNative

  target "CarnivalSDKReactNativeTests" do
    inherit! :search_paths
    # Pods for testing

    pod "React", path: "../node_modules/react-native", subspecs: [
      "Core",
      "CxxBridge" # Include this for RN >= 0.47
    ]

    pod "Carnival", "8.4.0-beta"
    pod "Kiwi", "2.4.0"
    pod "OCMock", "3.1.2"

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod "yoga", path: "../node_modules/react-native/ReactCommon/yoga"

    # Third party deps podspec link
    pod "Folly", podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  end
end
